# Generated by Django 4.2.4 on 2023-08-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='article',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Product Article'),
        ),
    ]
