# Generated by Django 4.2.4 on 2023-08-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
    ]
