# Generated by Django 4.2.4 on 2023-08-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category name')),
                ('slug', models.SlugField(max_length=70, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/category', verbose_name='Image')),
            ],
        ),
    ]
