# Generated by Django 4.2.4 on 2023-09-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_options_remove_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='shop.category'),
        ),
    ]
