# Generated by Django 4.2.4 on 2023-09-06 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=300, upload_to='images/media'),
        ),
        migrations.AlterField(
            model_name='image',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.media'),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(max_length=512, verbose_name='Image URL'),
        ),
    ]
