# Generated by Django 4.2.4 on 2023-09-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_image_image_alter_image_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='details',
            field=models.TextField(blank=True, verbose_name='Details'),
        ),
    ]
