# Generated by Django 4.2.4 on 2023-09-06 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='details',
        ),
    ]
