# Generated by Django 4.2.4 on 2023-09-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_product_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
